---
pipeline:
  molecule:
    image: lowess/drone-molecule:2.6.8
    pull: true
    task: test

    environment:
      - CI_UUID=_molecule_${DRONE_COMMIT_SHA}
    secrets: [git_ssh_key]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - molecule_${DRONE_COMMIT_SHA}:/tmp
